### ISSUE TITLE
Add an option to disable and enable apps with pm disable-user

### ISSUE THREAD

**Issue by YoranSys** [ibilux/MobyDroid#14]
Hello, 
I like MobyDroid but a killing feature for me would be to implement `pm disable-user` for disabling some apps and revert back if wanted.

Some example command:
- `adb shell pm disable-user --user 0 <package_to_disable>`
- `adb shell pm enable  <package_to_enable>`

More info : 
https://www.xda-developers.com/disable-system-app-bloatware-android/

**Comment by ibilux** [comment]
@YoranSys I'll try to implement it soon.

**Comment by TheShooter** [comment]
Hello @YoranSys, I think you might like this project [UAD](https://github.com/0x192/universal-android-debloater/) so instead of create this feature to MobyDroid, which consumes so much time and efforts, you can use uad for now. and let Bilux
 focus on maintaining this project only. just saying that to reduce the efforts. thank you.

**Comment by YoranSys** [comment]
Thanks for the advice @TheShooter  I will try UAD
